target_policy:
  alpha: 1.0
  beta: 6.5 
  gamma: 1.5
  factor_A: 8.0

waverider_policy:
  r: 2.5
  c: 1.5
  eta_rep: 1.2
  nu_rep: 1.5
  eta_damp: 3.0
  nu_damp: 2.0
  enable_repulsor: true
  enable_damper: true
  occupancy_threshold: 0.01
  run_all_levels: false
  lowest_level_radius: 2.0 # range that obstacles are considered, only used if use_only_lowest_level=true, otherwise res. dep. distance
  use_only_lowest_level: true # if true: all at highest available (leaf) resolution

velocity_controller:
  k: 2.0
