target_policy:
  alpha: 1.0
  beta: 6.0 
  gamma: 1.0
  factor_A: 10.0

waverider_policy:
  r: 1.3
  c: 1.5
  eta_rep: 4.0
  nu_rep: 3.0
  eta_damp: 14.0
  nu_damp: 2.5
  enable_repulsor: true
  enable_damper: true
  occupancy_threshold: 0.01
  run_all_levels: false
  lowest_level_radius: 3.0
  use_only_lowest_level: true

velocity_controller:
  k: 2.0
